### ISSUE TITLE
Grasped object cannot be picked up

### ISSUE THREAD

**Issue by ditoec** [JenniferBuehler/grasp-execution-pkgs#1]
Hi Jennifer :)

First of all I want to say thank you so much for such amazing works that you've got here, it really helps me a lot for my research. So I follow you grasp execution with move it tutorial, and I already got to the point where I call the grasp_cube_test node and the jaco arm was able to grasp the cube. I already attached the cube to the robot in moveit, but when I tried to lift it just by several cm, the cube just fell down. I tried to enable do_surface in the cube planner, but still it didn't solve my problem. Is there any config in the grasping function that I can change in order to solve this matter? Thank you

**Comment by ditoec** [comment]
Sorted :) I just realized the mechanism of grasp fix plugin. Previously I tried to rely grasping in physics alone, which was why it failed. But actually, if we can get force feedback from gazebo in order to guide grasping process, we can also relay the joint control to the real robot so it can grasp physical object, provided that we have good object localisation method and precise object model. Sorry I've just learn all jaco , moveit, and gazebo stuff in less than a week, so this idea might be wrong, I'm just trying to find out how to grasp stuff in real robot, knowing that the finger joints only give position feedback. I look into your graspit! tutorial and I wonder if we can use the result of that grasp planning and combine it with moveit! to perform simple pick and place operation in real robot. Anyway, great job!

**Comment by JenniferBuehler** [comment]
Thanks for the positive feedback :)

Yes, the grasp fix plugin may sometimes still be required also in newer Gazebo versions. The Gazebo version coming with ROS are always a bit "behind" in the version, so hopefully the plugin won't be required any more some time soon.
The "force feedback" from the Gazebo collision contact points could indeed be used to control the joint movement, e.g. stopping the fingers from closing when the object is already grasped. However doing this in simulation _and_ the real robot at the same time is almost guaranteed not to work, for reasons you already mentioned, like preciseness of object shape and differences in the actual execution on the real robot and in simulation. Also, it is _either_ gazebo _or_ the real robot you are running, as the simulation just replaces the real robot to allow for quick testing. Gazebo does _not mirror_ what the real robot is doing at the same time. It simulates its own world, so it cannot be used to act as feedback the real robot. It could only be used to feedback the joint control on the simulation itself, e.g. stop finger movement upon collision. Sorry I'm probably just stating the obvious ;) Anyway, the best way to approach this would be to simulate force-feedback sensors on the fingers, and then handle this in a robot-independent fashion in the joint trajectory execution. However the Jaco doesn't have force feedback, so there's little point in adding this in the simulation, which is why I haven't done this.

You're right, the grasp planning with GraspIt! can be used for the grasp execution. The tutorial (once finished) will include an example of this. So you won't have to always use the same grasp... right now in the tutorial only one grasp is used, which only works for the cube. This limitation is removed by using the grasp planner. Hang in there until the tutorial is updated :)

Thanks again for your feedback!

**Comment by ditoec** [comment]
Hi Jennifer,

Thanks for the very detailed explanation :) . So based on your experience, in this version of Gazebo that comes with ROS, it is still impossible to grasp the object using physics alone, even though we have tune the surface m1&m2 parameter of the box sdf and tune the force of the finger in the robot URDF? Well I've tried the first one at least and increasing m1&m2 parameter didn't work.

Yes I'm looking forward to the tutorial of using the grasp planner for grasp execution. Thanks very much again :)

**Comment by JenniferBuehler** [comment]
I wouldn't say it's impossible, but it may require a lot of tuning, which could still lead to unstable situations (e.g. when force is increased out of proportion, the robot could again explode sometimes). 
The object and finger surface/material parameters of the Jaco and the test cube are already configured such that grasping with physics only should work - both cube and fingers should be like a sticky sandpaper or something like that, but that still doesn't alleviate the problem. Maybe in Gazebo 7 it works, but haven't tried it yet.
