### ISSUE TITLE
Question: regarding placement of cube after grasping

### ISSUE THREAD

**Issue by karthikm-0** [JenniferBuehler/grasp-execution-pkgs#16]
Hi Jennifer,

I am trying to place the cube after the Jaco grasps it. While I can get it to place the object on a specific area of the table (hand-crafted grasp), I would like to maintain the original orientation of the cube. Is there a way to specify a constraint on the EEF's orientation so that the fingers face downward before ungrasping? Thanks!

**Comment by JenniferBuehler** [comment]
Hi, to confirm I understand your question correctly: You are doing it like in [this tutorial](https://github.com/JenniferBuehler/grasp-execution-pkgs/wiki/Grasping-with-Jaco-in-Gazebo-with-MoveIt) and in [step 8](https://github.com/JenniferBuehler/grasp-execution-pkgs/wiki/Grasping-with-Jaco-in-Gazebo-with-MoveIt#step-8-attach-the-cube-to-robot-in-moveit-and-move-the-arm) you would like the arm to move to a specific orientation? And you are moving the arm with the RViz MoveIt control panel?
In this case you have to set the desired orientation with the RViz control (the interactive control markers) before you move the arm which is currently holding the cube.

**Comment by karthikm-0** [comment]
Hi Jennifer,

Sorry for not being clear; I am referring to [this tutorial](https://github.com/JenniferBuehler/grasp-execution-pkgs/wiki/Automated-grasping-tutorial). I added a method to your script (SimpleAutomatedGraspExecution) using the reach method as a template to achieve the place (after picking). However, I have two issues:

1. The issue mentioned in this post that the arm does not place the cube back in its original orientation (which means it cannot be subsequently picked up again). Please see the image below for the visual:

![Jaco_Place](https://user-images.githubusercontent.com/39807420/71825231-69073200-3069-11ea-9f5e-1fd15e0d795e.png)

To set the eef orientation, I am using frame_id = "tabletop_ontop". Should I be using a different frame_id in order to set the orientation correctly? Furthermore, using this frame_id, I cannot set other quaternions (than 0,0,0,0) as they are not feasible for MoveIt. 

2. The second issue is that ideally once the cube has been grasped, I would like to set the eef's final position with respect to the world but this is not possible as the planner is unable to find a feasible trajectory (once again I am using frame_id = "tabletop_ontop" to set the final pose on the table). Would you suggest an alternative frame_id?

I could post the modified script if this would be more helpful. 

Thanks!

**Comment by JenniferBuehler** [comment]
Hi, thanks for the clarification.

To be sure I understand you correctly: you modified the `reach` method and you are setting the desired orientation (quaternion) in the [graspGoal.grasp.grasp.grasp_pose](https://github.com/JenniferBuehler/grasp-execution-pkgs/blob/3cfd1ef47a449a38f96b561711d53e16c455d0dd/grasp_execution/src/SimpleAutomatedGraspExecution.cpp#L310)?

It should be possible to pick the cube up again even if it is not in the original orientation, as long as the arm can still reach the grasping pose. But if you have only one grasp, then the "up" side of the cube should always point up, or the arm would collide with the table when trying to grasp it.

The solution here is to have several grasps, one for each side of the cube (which anyway makes sense for something symmetric like the cube). Then evaluate them all and find an eligible one. This is anyway how reaching/grasping pipelines are mostly designed, and one reason why grasp databases often contain several grasps for one object: all available grasps are evaluated for the current setup (e.g. reachability, collision, etc), and then a suitable grasp is picked and executed.
The code here is just a simple example implementation (as the name suggests) to show how to use the pipeline. For a proper setup, you have to make your own implementation according to your needs, which you are already doing anyway :)

So if you want to do the "proper implementation" (in which several grasps are supported), here a suggestion/thought:

You could modify the existing hand-crafted grasp to generate more grasps for the cube, by changing the EEF grasp pose such that it grasps the cube from a different side (same effect as rotating the cube underneath the grasping EEF). This requires a small piece of code, but for cases like the cube which are symmetric all around, it is worth it, because you can generate a lot more grasps from only one pre-computed (e.g. via GraspIt) grasp.

Then you can modify the code (`simple_automated_grasp_execution.cpp`) to evaluate several grasps and then pick the most eligible one. In `SimpleAutomatedGraspExecution`, you basically have to try [trajectoryPlanner->requestTrajectory](https://github.com/JenniferBuehler/grasp-execution-pkgs/blob/3cfd1ef47a449a38f96b561711d53e16c455d0dd/grasp_execution/src/SimpleAutomatedGraspExecution.cpp#L244) for a grasp pose, and if that succeeds, then the grasp pose can be reached, and the grasp is eligible. E.g. you may want to provide a `SimpleAutonmatedGraspExecution::checkGrasp(...)` to check for the eligibility of the grasp (side note: if you want to optimize later, you can cache the MoveIt motion plan result, because that result takes some time to get... then you can re-use this later at execution time). Then once an eligible grasp is found, you can execute it (possibly using the cached result). How you implement this in terms of software design is entirely up to you, the simple example code can be used to get an idea of how things work.

Or, if that all would take too much time which is not justified for your cause, then you can still try to get the placing done such that the cube stays in the same orientation (or at least it lands with the same side up). However there is still no guarantee that this single grasp you are using will succeed, even if the orientation is *exactly* the same as in the beginning: if the cube is at a different pose, it is always possible that no motion plan for this particular pose can be computed (in that case you would get errors from the MoveIt motion planner). This may be the issue which you are experiencing right now, as you descibe in 2. MoveIt fails to plan a path, because it tries to accurately reach the target pose, but either the Jaco arm just can't, or MoveIt motion planner happened to not sample a state from which a solution accurate enough could be found (MoveIt results are random, so if you try n times, it may suddenly succeed). This issue can often be relaxed by allowing a higher tolerance for the EEF pose and orienation. See also [parameters here](https://github.com/JenniferBuehler/grasp-execution-pkgs/blob/3cfd1ef47a449a38f96b561711d53e16c455d0dd/grasp_execution/src/SimpleAutomatedGraspExecution.cpp#L65) which you may modify.

Ah, and BTW, the frame ID for the target reach pose should not matter, as long as the pose and orientation match (after tf transformations) the desired goal pose in world coordinates.

**Comment by JenniferBuehler** [comment]
P.S.: The parameters I mentioned at the end of my last post are actually documented in the example config file [here](https://github.com/JenniferBuehler/grasp-execution-pkgs/blob/3cfd1ef47a449a38f96b561711d53e16c455d0dd/grasp_execution/config/SimpleAutomatedGraspTemplate.yaml#L53).  I should really tidy this up some time...

**Comment by karthikm-0** [comment]
Hi Jennifer,

Thank you for this very informative response. I am attempting to do the pick and place with multiple objects and it seems that no matter what happens, I cannot execute multiple pick and place in one shot. There are either collisions between the gripper's fingers and the cube or cubes get tipped over. The obvious fix is to adjust the cube's pose through Gazebo when this happens (translating the cube when the gripper is stuck or resetting the rotation when it tips over). For my specific use case of multiple object pick-and-place, would you suggest a different approach? Perhaps using either pre-generated GraspIt grasps from file or online planning (the other approaches in your automated grasping tutorial)? 

I was also curious as to whether there are other pipelines that I might be able to use to accomplish this. My goal is less about grasping and about the interaction of users and the robot. To be frank, it would be okay if the cube were directly attached as long as the gripper is in the "correct" pose prior to grasping. Would disabling the grasping action server and using: graspHandler->attachObjectToRobot(...) make this possible? I assume this implies that the cube's pose will now update in accordance with the robot's wrist link. This is a bit of an extreme measure but the pick-and-place would need to be robust so that I can explore my specific research question.

I really appreciate your package as it has given me an opportunity to really learn how reaching and grasping actually works. Thank you once again!

**Comment by JenniferBuehler** [comment]
Yes, grasping is not an easy undertaking. I can imagine that if you try to pick up several objects in one shot, something goes wrong along the line every time. If you need the system to be a lot more robust/reliable, some more work would have to go in, the "simple" grasp execution is not an ideal fit then.

If your goal is more about user interaction, I would indeed try a simpler approach. Trying to simulate the grasping as accurate as possible is then just a lot of effort with no benefits for your research question. You could simply move the arm to the grasp pose, and then attach the cube to the robot once it's in place (as you suggested).
For that, you could write a simple Gazebo Model Plugin (instead of using the [grasp fix plugin](https://github.com/JenniferBuehler/gazebo-pkgs/tree/master/gazebo_grasp_plugin) which is used here) to support the attaching of the cube. For example, you could write one which accepts a trigger message (easiest if it's just a ROS message) which you send out once the arm is in place. Upon receipt of the trigger message, you attach the cube (as is done in the [grasp fix plugin](https://github.com/JenniferBuehler/gazebo-pkgs/tree/master/gazebo_grasp_plugin)), and upon another trigger message, it is released. That's all you need to do then.
(1) move the arm to the target, for which you can use (modify as needed) the code from this repo and (2) once the arm is in place, send a trigger message to the gazebo plugin (instead of doing the proper grasping) then (3) move the arm to the target and (4) send another trigger message for release.
That's just an idea... many more ways to go about it ;)

**Comment by karthikm-0** [comment]
Hi Jennifer,

Thank you for the response! I actually did just that and it seems to work pretty well. This is more out of curiosity but what is state-of-the-art in grasping? I am wondering if there are more recent methods one could use to achieve reliable grasping. I noticed there are some newer techniques that use CNNs. Would you know of any others? I may attempt to integrate it with your existing project to see how well it would perform.

**Comment by JenniferBuehler** [comment]
You probably refer to grasp planners other than Graspit? 
I have been out of the loop for a while in regards to grasping so there may be something I haven't yet heard about. Here a few which I've been wanting to try but never got around to it (life is just too busy :'() 

* [Simox motion planning](http://simox.sourceforge.net/) and [github link](https://gitlab.com/Simox/simox/wikis/home). There is also a grasp planner in there. 
* [Haptix project from OSRF](http://gazebosim.org/haptix). But I don't know what the newest state of this is. 
* There is an package that generates a grasp based on the pose and shape of a simple object, but last I've heard it's been abandoned because the maintainer is too busy: [moveit_simple_grasps](https://github.com/davetcoleman/moveit_simple_grasps) 
* there's a package that uses SVMs on point cloud data to generate and visualizes grasps, with a demo with MoveIt integration, but it's specific to the Baxter robot interface: [grasp_selection](https://github.com/atenpas/grasp_selection) 
* Here's one using moveit and [AGILE grasp](http://wiki.ros.org/agile_grasp)
* Here's one for simple grippers, it's a ROS package for grasp calculation on unknown and known objects based on point clouds. Paper is [Fischinger, A. Weiss, M. Vincze. Learning Grasps with Topographic
Features. The International Journal of Robotics Research, 2015](http://ijr.sagepub.com/content/34/9/1167.full.pdf+html). Technical description [here](http://wiki.ros.org/haf_grasping)

Sorry if the info may be a bit out of date but I hope it helps anyway :)
