### ISSUE TITLE
Error: Only support 1 axis

### ISSUE THREAD

**Issue by marooncn** [JenniferBuehler/grasp-execution-pkgs#8]
I install this package according to  [Installation](https://github.com/JenniferBuehler/grasp-execution-pkgs/wiki/Installation) and after successful compilation, I continue to run the grasp demo according to [Grasping with Jaco in Gazebo](https://github.com/JenniferBuehler/grasp-execution-pkgs/wiki/Grasping-with-Jaco-in-Gazebo), but when I input
`roslaunch grasp_execution_jaco_tutorial jaco_on_table_gazebo_objects_controlled.launch` 
or
`roslaunch grasp_execution_jaco_tutorial jaco_on_table_gazebo_objects_controlled.launch load_grasp_fix:=true`
there comes an error
> [FATAL] [1522491539.404222264, 0.096000000]: Only support 1 axis

Why is it? How can I solve it? Thank you.

**Comment by JenniferBuehler** [comment]
Hi,

thanks for reporting this. You are now the 3rd person experiencing this issue, I guess you are using Kinetic too?

I have just tried to reproduce it today (without success unfortunately, it works for me). I will try my best to find the issue anyway. The issue is currently being discussed [in issue 16 of jaco-arm-pkgs](https://github.com/JenniferBuehler/jaco-arm-pkgs/issues/16). Could you please also do the following and report in the other issue what your program output is:

- pull moveit-pkgs
- pull joint-control-pkgs
- re-compile and re-run
- report error which should be repeatedly being printed now

Thanks!

**Comment by marooncn** [comment]
Thank you for your instant responce. Actually my ROS version is indigo and the first time I run the command it can work. But after I install and compile another package in the same work space it cannot work any more. 
When I go back to Lab I will try as you said and give you feedback :)

**Comment by marooncn** [comment]
Hi, @JenniferBuehler It works!
I pull moveit-pkgs(indigo branch) and pull joint-control-pkgs then I re-compile and re-run. Now it works except the continous error report as the following

> [ERROR] [1522505915.483918160, 51.646000000]: GazeboJointStatePublisher: Only support 1 axis, got 0, cannot write angle for joint 'base_to_jaco_on_table'
[ERROR] [1522505915.484581525, 51.647000000]: GazeboJointStatePublisher: Only support 1 axis, got 0, cannot write angle for joint 'base_to_jaco_on_table'
[ERROR] [1522505915.485591176, 51.648000000]: GazeboJointStatePublisher: Only support 1 axis, got 0, cannot write angle for joint 'base_to_jaco_on_table'
[ERROR] [1522505915.486679553, 51.649000000]: GazeboJointStatePublisher: Only support 1 axis, got 0, cannot write angle for joint 'base_to_jaco_on_table'
[ERROR] [1522505915.487783903, 51.650000000]: GazeboJointStatePublisher: Only support 1 axis, got 0, cannot write angle for joint 'base_to_jaco_on_table'
[ERROR] [1522505915.488728993, 51.651000000]: GazeboJointStatePublisher: Only support 1 axis, got 0, cannot write angle for joint 'base_to_jaco_on_table'
But it doesn't affect the grasp demo running.

What's more when it runs Step 4. "Home" the arm, it fails to "home" because at the starting state the grasp loose and the cube falls down.

**Comment by JenniferBuehler** [comment]
Hi, can you please pull the new version of joint-control-pkgs, I have fixed this just then so the errors should have gone now.

Can you explain again what you mean with the "Home" failure? So it starts to move, the cube falls down, and the rest of the movement then fails? Are there any errors printed?

Did you try to run it with the grasp fix plugin

``roslaunch grasp_execution_jaco_tutorial jaco_on_table_gazebo_objects_controlled.launch load_grasp_fix:=true``

and it also fails?

**Comment by marooncn** [comment]
There are no errors report when I pull the new version of joint-control-pkgs, thank you.

"Home" failure means:
![peek 2018-04-03 13-37](https://user-images.githubusercontent.com/29606478/38231259-65d4e282-3744-11e8-9e2f-9013a4f59655.gif)
And at the first step I run it with the grasp fix plugin
`roslaunch grasp_execution_jaco_tutorial jaco_on_table_gazebo_objects_controlled.launch load_grasp_fix:=true`

**Comment by JenniferBuehler** [comment]
That's not really a "Home" failure (in terms of the arm movement), it has just not been able to grasp the cube, that's why it slips out of the grippers. If the grasp plugin is active, this means that there would not even have been enough contact with the cube in the first place, which is a bit weird because this is the pre-defined pose where it should have enough contact.

Can you send the output of the terminal where you launched ``roslaunch grasp_execution_jaco_tutorial jaco_on_table_gazebo_objects_controlled.launch load_grasp_fix:=true`` please?

**Comment by JenniferBuehler** [comment]
Since I haven't heard back, I presume this has been resolved? I will close this for now. Please re-open if you are still experiencing the issue with the newest package updates. You also don't need to use the "indigo" branch of moveit-pkgs any more, just the master.
